project:
  type: website
  output-dir: "docs"

website:
  title: "ejemplo_prueba"
  navbar:
    background: "#B4EEB4"
    foreground: "#8FBC8F"
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Sobre la página
      - href: hola.qmd
        text: holaaa

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

